# -*- coding: utf-8 -*-
"""Projeto aplicado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQVPlxCViRzL9_-oXIVtiE2xqvYzMKLt
"""

import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
df = pd.read_cvs('Cliente_SP.cvs')
print(df.shape)
print(df.head())
print(df.columns)
print(df.info())
df.describe()

import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns
df = pd.read_csv('CLIENTES_ENTREGAS_SP.csv')
print(df.shape)
print(df.head())
print(df.columns)
print(df.info())
df.describe()